# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mulintirohan159@gmail.com
author_name: RohithNai537
contract_name: civic_chain
deployment_language: python
preset_name: starter
project_name: CivicChain-contracts

